### ISSUE TITLE
Version de docker compose sur le README.md

### ISSUE THREAD

**Issue by terence-meunier** [cbouvat/docker-laravel#1]
Salut Camille, pour la version demandé de docker compose, la version 3.9 correspond à la version à utilisé dans le fichier docker-compose.yml, mais ce n'est pas la version du logiciel, car celle-ci en est à la version 1.29.2, cela n'est donc pas très clair dans le README.

**Comment by cbouvat** [comment]
Merci, je vais modifier cela.

**Comment by cbouvat** [comment]
@terence-meunier c'est modifié !
